### ISSUE TITLE
links_latest.yml VCR cassette is too big

### ISSUE THREAD

**Issue by dominicsayers** [Xenapto/contact-data#10]
Makes this a huge gem to download :-1: 

`contact-data/spec/support/cassettes/links_latest.yml`

**Comment by xenapto-support** [comment]
Thanks for the message, we'll get back to you as soon as
possible!

On June 18, 2015 at 12:29 PM Xenapto/contact-data wrote:

Makes this a huge gem to download :-1:

`contact-data/spec/support/cassettes/links_latest.yml`

---

Reply to this email directly or view it on GitHub:

https://github.com/Xenapto/contact-data/issues/10 ( https://github.com/Xenapto/contact-data/issues/10 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=Xenapto&uv_contact_url=support.xenapto.com&uv_experience=email )
